### ISSUE TITLE
IBM Think

### ISSUE THREAD

**Issue by Issen007** [hassenius/terraform-module-icp-deploy#10]
Hi Hassenius,
Don't know how I can get hold of you in any better way then this.

But will you come to IBM Think in San Francisco in Feb?
If yes, is it possible to catch up? We have done a lot of cool work for VMware and RHEL that can be reused for your project. 

Cheers
Christian

**Comment by hassenius** [comment]
Hey @Issen007 , 
yes, I am indeed going to Think, and it would be great to meet up.
Would love to see what you guys have done, and how it can be reused.

If you reach out on hans.moen@ie.ibm.com we can figure out the logistics for the week.
